image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      gem install bundler
      bundle install
  - command: |
      bin/rails db:create db:migrate
      bin/rails s -b 0.0.0.0
ports:
  - port: 3000
    onOpen: open-preview
